apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: regional-test
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-hostpath
  resources:
    requests:
      storage: 1Gi
  volumeMode: Block
