// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/virt-handler/node-local-hotplug/v1/nodelocalhotplug.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:

	pkg/virt-handler/node-local-hotplug/v1/nodelocalhotplug.proto

It has these top-level messages:

	Empty
	HotplugVolumeSourceSpec
	HotplugDiskTargetSpec
	HotplugAttachSpec
	AttachVolumeRequest
	AttachVolumeResponse
	RemoveVolumeRequest
	RemoveVolumeResponse
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// PVC or DataVolume reference (exactly one must be set).
type HotplugVolumeSourceSpec struct {
	PvcClaimName   string `protobuf:"bytes,1,opt,name=pvc_claim_name,json=pvcClaimName" json:"pvc_claim_name,omitempty"`
	DataVolumeName string `protobuf:"bytes,2,opt,name=data_volume_name,json=dataVolumeName" json:"data_volume_name,omitempty"`
}

func (m *HotplugVolumeSourceSpec) Reset()                    { *m = HotplugVolumeSourceSpec{} }
func (m *HotplugVolumeSourceSpec) String() string            { return proto.CompactTextString(m) }
func (*HotplugVolumeSourceSpec) ProtoMessage()               {}
func (*HotplugVolumeSourceSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HotplugVolumeSourceSpec) GetPvcClaimName() string {
	if m != nil {
		return m.PvcClaimName
	}
	return ""
}

func (m *HotplugVolumeSourceSpec) GetDataVolumeName() string {
	if m != nil {
		return m.DataVolumeName
	}
	return ""
}

// disk target
type HotplugDiskTargetSpec struct {
	// JSON of kubevirt.io/api/core/v1.Disk (disk/lun/cdrom, cache, serial, blockSize, ...).
	// When non-empty, overrides the simple `disk` field above.
	DiskJson []byte `protobuf:"bytes,1,opt,name=disk_json,json=diskJson,proto3" json:"disk_json,omitempty"`
	ReadOnly bool   `protobuf:"varint,2,opt,name=read_only,json=readOnly" json:"read_only,omitempty"`
}

func (m *HotplugDiskTargetSpec) Reset()                    { *m = HotplugDiskTargetSpec{} }
func (m *HotplugDiskTargetSpec) String() string            { return proto.CompactTextString(m) }
func (*HotplugDiskTargetSpec) ProtoMessage()               {}
func (*HotplugDiskTargetSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HotplugDiskTargetSpec) GetDiskJson() []byte {
	if m != nil {
		return m.DiskJson
	}
	return nil
}

func (m *HotplugDiskTargetSpec) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

// Typed attach: volume source + disk_json
type HotplugAttachSpec struct {
	Name         string                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	VolumeSource *HotplugVolumeSourceSpec `protobuf:"bytes,2,opt,name=volume_source,json=volumeSource" json:"volume_source,omitempty"`
	Disk         *HotplugDiskTargetSpec   `protobuf:"bytes,3,opt,name=disk" json:"disk,omitempty"`
	BootOrder    uint32                   `protobuf:"varint,4,opt,name=boot_order,json=bootOrder" json:"boot_order,omitempty"`
}

func (m *HotplugAttachSpec) Reset()                    { *m = HotplugAttachSpec{} }
func (m *HotplugAttachSpec) String() string            { return proto.CompactTextString(m) }
func (*HotplugAttachSpec) ProtoMessage()               {}
func (*HotplugAttachSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HotplugAttachSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HotplugAttachSpec) GetVolumeSource() *HotplugVolumeSourceSpec {
	if m != nil {
		return m.VolumeSource
	}
	return nil
}

func (m *HotplugAttachSpec) GetDisk() *HotplugDiskTargetSpec {
	if m != nil {
		return m.Disk
	}
	return nil
}

func (m *HotplugAttachSpec) GetBootOrder() uint32 {
	if m != nil {
		return m.BootOrder
	}
	return 0
}

type AttachVolumeRequest struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	VmiName   string `protobuf:"bytes,2,opt,name=vmi_name,json=vmiName" json:"vmi_name,omitempty"`
	// JSON with name, disk, volumeSource, dryRun (same shape as virt-api addvolume; alternative to attach_spec).
	AttachOptionsJson []byte             `protobuf:"bytes,3,opt,name=attach_options_json,json=attachOptionsJson,proto3" json:"attach_options_json,omitempty"`
	AttachSpec        *HotplugAttachSpec `protobuf:"bytes,4,opt,name=attach_spec,json=attachSpec" json:"attach_spec,omitempty"`
}

func (m *AttachVolumeRequest) Reset()                    { *m = AttachVolumeRequest{} }
func (m *AttachVolumeRequest) String() string            { return proto.CompactTextString(m) }
func (*AttachVolumeRequest) ProtoMessage()               {}
func (*AttachVolumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AttachVolumeRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AttachVolumeRequest) GetVmiName() string {
	if m != nil {
		return m.VmiName
	}
	return ""
}

func (m *AttachVolumeRequest) GetAttachOptionsJson() []byte {
	if m != nil {
		return m.AttachOptionsJson
	}
	return nil
}

func (m *AttachVolumeRequest) GetAttachSpec() *HotplugAttachSpec {
	if m != nil {
		return m.AttachSpec
	}
	return nil
}

type AttachVolumeResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *AttachVolumeResponse) Reset()                    { *m = AttachVolumeResponse{} }
func (m *AttachVolumeResponse) String() string            { return proto.CompactTextString(m) }
func (*AttachVolumeResponse) ProtoMessage()               {}
func (*AttachVolumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AttachVolumeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AttachVolumeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RemoveVolumeRequest struct {
	Namespace  string   `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	VmiName    string   `protobuf:"bytes,2,opt,name=vmi_name,json=vmiName" json:"vmi_name,omitempty"`
	VolumeName string   `protobuf:"bytes,3,opt,name=volume_name,json=volumeName" json:"volume_name,omitempty"`
	DryRun     []string `protobuf:"bytes,4,rep,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
}

func (m *RemoveVolumeRequest) Reset()                    { *m = RemoveVolumeRequest{} }
func (m *RemoveVolumeRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveVolumeRequest) ProtoMessage()               {}
func (*RemoveVolumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoveVolumeRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *RemoveVolumeRequest) GetVmiName() string {
	if m != nil {
		return m.VmiName
	}
	return ""
}

func (m *RemoveVolumeRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *RemoveVolumeRequest) GetDryRun() []string {
	if m != nil {
		return m.DryRun
	}
	return nil
}

type RemoveVolumeResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *RemoveVolumeResponse) Reset()                    { *m = RemoveVolumeResponse{} }
func (m *RemoveVolumeResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveVolumeResponse) ProtoMessage()               {}
func (*RemoveVolumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RemoveVolumeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RemoveVolumeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "kubevirt.virthandler.nodelocalhotplug.v1.Empty")
	proto.RegisterType((*HotplugVolumeSourceSpec)(nil), "kubevirt.virthandler.nodelocalhotplug.v1.HotplugVolumeSourceSpec")
	proto.RegisterType((*HotplugDiskTargetSpec)(nil), "kubevirt.virthandler.nodelocalhotplug.v1.HotplugDiskTargetSpec")
	proto.RegisterType((*HotplugAttachSpec)(nil), "kubevirt.virthandler.nodelocalhotplug.v1.HotplugAttachSpec")
	proto.RegisterType((*AttachVolumeRequest)(nil), "kubevirt.virthandler.nodelocalhotplug.v1.AttachVolumeRequest")
	proto.RegisterType((*AttachVolumeResponse)(nil), "kubevirt.virthandler.nodelocalhotplug.v1.AttachVolumeResponse")
	proto.RegisterType((*RemoveVolumeRequest)(nil), "kubevirt.virthandler.nodelocalhotplug.v1.RemoveVolumeRequest")
	proto.RegisterType((*RemoveVolumeResponse)(nil), "kubevirt.virthandler.nodelocalhotplug.v1.RemoveVolumeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeLocalHotplug service

type NodeLocalHotplugClient interface {
	AttachVolume(ctx context.Context, in *AttachVolumeRequest, opts ...grpc.CallOption) (*AttachVolumeResponse, error)
	RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error)
}

type nodeLocalHotplugClient struct {
	cc *grpc.ClientConn
}

func NewNodeLocalHotplugClient(cc *grpc.ClientConn) NodeLocalHotplugClient {
	return &nodeLocalHotplugClient{cc}
}

func (c *nodeLocalHotplugClient) AttachVolume(ctx context.Context, in *AttachVolumeRequest, opts ...grpc.CallOption) (*AttachVolumeResponse, error) {
	out := new(AttachVolumeResponse)
	err := grpc.Invoke(ctx, "/kubevirt.virthandler.nodelocalhotplug.v1.NodeLocalHotplug/AttachVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeLocalHotplugClient) RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error) {
	out := new(RemoveVolumeResponse)
	err := grpc.Invoke(ctx, "/kubevirt.virthandler.nodelocalhotplug.v1.NodeLocalHotplug/RemoveVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeLocalHotplug service

type NodeLocalHotplugServer interface {
	AttachVolume(context.Context, *AttachVolumeRequest) (*AttachVolumeResponse, error)
	RemoveVolume(context.Context, *RemoveVolumeRequest) (*RemoveVolumeResponse, error)
}

func RegisterNodeLocalHotplugServer(s *grpc.Server, srv NodeLocalHotplugServer) {
	s.RegisterService(&_NodeLocalHotplug_serviceDesc, srv)
}

func _NodeLocalHotplug_AttachVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeLocalHotplugServer).AttachVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.virthandler.nodelocalhotplug.v1.NodeLocalHotplug/AttachVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeLocalHotplugServer).AttachVolume(ctx, req.(*AttachVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeLocalHotplug_RemoveVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeLocalHotplugServer).RemoveVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.virthandler.nodelocalhotplug.v1.NodeLocalHotplug/RemoveVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeLocalHotplugServer).RemoveVolume(ctx, req.(*RemoveVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeLocalHotplug_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubevirt.virthandler.nodelocalhotplug.v1.NodeLocalHotplug",
	HandlerType: (*NodeLocalHotplugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AttachVolume",
			Handler:    _NodeLocalHotplug_AttachVolume_Handler,
		},
		{
			MethodName: "RemoveVolume",
			Handler:    _NodeLocalHotplug_RemoveVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/virt-handler/node-local-hotplug/v1/nodelocalhotplug.proto",
}

func init() {
	proto.RegisterFile("pkg/virt-handler/node-local-hotplug/v1/nodelocalhotplug.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0xda, 0xb2, 0xb6, 0xb7, 0xdd, 0xb4, 0xb9, 0xa0, 0x95, 0x2f, 0x51, 0x45, 0x3c, 0xf4,
	0xa5, 0xa9, 0x5a, 0x1e, 0xd1, 0x40, 0xe3, 0x43, 0x42, 0x13, 0x5a, 0x85, 0x8b, 0x78, 0x40, 0x48,
	0x91, 0x9b, 0x98, 0x36, 0x34, 0x89, 0x43, 0xec, 0x58, 0xea, 0x33, 0x2f, 0xbc, 0xf1, 0x6f, 0xf8,
	0x35, 0xfc, 0x18, 0xe4, 0x9b, 0xac, 0x4b, 0x45, 0x91, 0xd6, 0x69, 0x2f, 0x91, 0x7d, 0xee, 0xf5,
	0xf1, 0x39, 0xe7, 0x5a, 0x81, 0xd3, 0x64, 0x39, 0x1f, 0xea, 0x20, 0x55, 0x83, 0x05, 0x8b, 0xfd,
	0x90, 0xa7, 0xc3, 0x58, 0xf8, 0x7c, 0x10, 0x0a, 0x8f, 0x85, 0x83, 0x85, 0x50, 0x49, 0x98, 0xcd,
	0x87, 0x7a, 0x84, 0x28, 0x82, 0x05, 0xe6, 0x24, 0xa9, 0x50, 0x82, 0xf4, 0x97, 0xd9, 0x8c, 0x9b,
	0xe3, 0x8e, 0xf9, 0x14, 0x14, 0xce, 0x3f, 0xcd, 0x7a, 0x64, 0xd7, 0xe1, 0xce, 0xdb, 0x28, 0x51,
	0x2b, 0x3b, 0x80, 0x93, 0x77, 0x39, 0xfc, 0x49, 0x84, 0x59, 0xc4, 0xa7, 0x22, 0x4b, 0x3d, 0x3e,
	0x4d, 0xb8, 0x47, 0x9e, 0xc2, 0x61, 0xa2, 0x3d, 0xd7, 0x0b, 0x59, 0x10, 0xb9, 0x31, 0x8b, 0x78,
	0xd7, 0xea, 0x59, 0xfd, 0x26, 0x6d, 0x27, 0xda, 0x7b, 0x6d, 0xc0, 0x0b, 0x16, 0x71, 0xd2, 0x87,
	0x23, 0x9f, 0x29, 0xe6, 0x6a, 0x3c, 0x9e, 0xf7, 0x55, 0xb0, 0xef, 0xd0, 0xe0, 0x39, 0xab, 0xe9,
	0xb4, 0x3f, 0xc0, 0xbd, 0xe2, 0xaa, 0x37, 0x81, 0x5c, 0x7e, 0x64, 0xe9, 0x9c, 0x2b, 0xbc, 0xe8,
	0x21, 0x34, 0xfd, 0x40, 0x2e, 0xdd, 0x6f, 0x52, 0xc4, 0x78, 0x47, 0x9b, 0x36, 0x0c, 0x70, 0x2e,
	0x45, 0x6c, 0x8a, 0x29, 0x67, 0xbe, 0x2b, 0xe2, 0x70, 0x85, 0xc4, 0x0d, 0xda, 0x30, 0xc0, 0x24,
	0x0e, 0x57, 0xf6, 0x8f, 0x0a, 0x1c, 0x17, 0x9c, 0x67, 0x4a, 0x31, 0x6f, 0x81, 0x7c, 0x04, 0x6a,
	0x25, 0xb9, 0xb8, 0x26, 0x5f, 0xe1, 0xa0, 0x50, 0x28, 0xd1, 0x21, 0x52, 0xb5, 0xc6, 0x67, 0xce,
	0x75, 0x23, 0x73, 0xfe, 0x13, 0x13, 0x6d, 0xeb, 0x12, 0x42, 0xa6, 0x50, 0x33, 0xd2, 0xbb, 0x55,
	0xa4, 0x7f, 0xb9, 0x33, 0xfd, 0x66, 0x34, 0x14, 0xc9, 0xc8, 0x63, 0x80, 0x99, 0x10, 0xca, 0x15,
	0xa9, 0xcf, 0xd3, 0x6e, 0xad, 0x67, 0xf5, 0x0f, 0x68, 0xd3, 0x20, 0x13, 0x03, 0xd8, 0x7f, 0x2c,
	0xe8, 0xe4, 0xf6, 0x73, 0x71, 0x94, 0x7f, 0xcf, 0xb8, 0x54, 0xe4, 0x11, 0x34, 0x8d, 0x77, 0x99,
	0x30, 0xef, 0x32, 0x8c, 0x2b, 0x80, 0xdc, 0x87, 0x86, 0x8e, 0x82, 0xf2, 0xc0, 0xea, 0x3a, 0x0a,
	0x70, 0xa6, 0x0e, 0x74, 0x18, 0xf2, 0xb9, 0x22, 0x51, 0x81, 0x88, 0x65, 0x3e, 0x9a, 0x2a, 0x8e,
	0xe6, 0x38, 0x2f, 0x4d, 0xf2, 0x0a, 0xce, 0xe8, 0x0b, 0xb4, 0x8a, 0x7e, 0x99, 0x70, 0x0f, 0x05,
	0xb6, 0xc6, 0xcf, 0x77, 0xf6, 0x7e, 0x35, 0x42, 0x0a, 0x6c, 0xbd, 0xb6, 0xcf, 0xe1, 0xee, 0xa6,
	0x3b, 0x99, 0x88, 0x58, 0x72, 0xd2, 0x85, 0xba, 0xcc, 0x3c, 0x8f, 0x4b, 0x89, 0xe6, 0x1a, 0xf4,
	0x72, 0x6b, 0x2a, 0x11, 0x97, 0x92, 0xcd, 0xd7, 0xce, 0x8a, 0xad, 0xfd, 0xd3, 0x82, 0x0e, 0xe5,
	0x91, 0xd0, 0xfc, 0x96, 0xa2, 0x7a, 0x02, 0xad, 0xf2, 0xcb, 0xaf, 0x62, 0x15, 0xf4, 0xfa, 0xd5,
	0x93, 0x13, 0xa8, 0xfb, 0xe9, 0xca, 0x4d, 0xb3, 0xb8, 0x5b, 0xeb, 0x55, 0xfb, 0x4d, 0xba, 0xef,
	0xa7, 0x2b, 0x9a, 0xc5, 0xc6, 0xd6, 0xa6, 0x92, 0x9b, 0xdb, 0x1a, 0xff, 0xae, 0xc0, 0xd1, 0x85,
	0xf0, 0xf9, 0x7b, 0x13, 0x6c, 0x91, 0x26, 0xf9, 0x65, 0x41, 0xbb, 0x1c, 0x1c, 0x39, 0xbd, 0xfe,
	0x44, 0xb6, 0x3c, 0xa7, 0x07, 0x2f, 0x6e, 0x7a, 0x3c, 0x37, 0x66, 0xef, 0xa1, 0xa2, 0xb2, 0xe7,
	0x5d, 0x14, 0x6d, 0x99, 0xda, 0x2e, 0x8a, 0xb6, 0x45, 0x6d, 0xef, 0xbd, 0xaa, 0x7d, 0xae, 0xe8,
	0xd1, 0x6c, 0x1f, 0x7f, 0x9f, 0xcf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x84, 0x89, 0xab, 0x96,
	0x7f, 0x05, 0x00, 0x00,
}
