// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/virt-handler/node-local-hotplug/v1/nodelocalhotplug.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:

	pkg/virt-handler/node-local-hotplug/v1/nodelocalhotplug.proto

It has these top-level messages:

	Device
	AttachDeviceRequest
	AttachDeviceResponse
	DetachDeviceRequest
	DetachDeviceResponse
*/
package v1

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// DeviceFormat tells virt-handler how to interpret the host path
// provided by the caller and how to translate it into a libvirt disk
// source.
type DeviceFormat int32

const (
	DeviceFormat_DEVICE_FORMAT_UNSPECIFIED DeviceFormat = 0
	DeviceFormat_DEVICE_FORMAT_BLOCK       DeviceFormat = 1
	DeviceFormat_DEVICE_FORMAT_FILE        DeviceFormat = 2
)

var DeviceFormat_name = map[int32]string{
	0: "DEVICE_FORMAT_UNSPECIFIED",
	1: "DEVICE_FORMAT_BLOCK",
	2: "DEVICE_FORMAT_FILE",
}

var DeviceFormat_value = map[string]int32{
	"DEVICE_FORMAT_UNSPECIFIED": 0,
	"DEVICE_FORMAT_BLOCK":       1,
	"DEVICE_FORMAT_FILE":        2,
}

func (x DeviceFormat) String() string {
	return proto.EnumName(DeviceFormat_name, int32(x))
}

func (DeviceFormat) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// TargetBus selects the libvirt <target bus='...'/> attribute on the
// generated disk. Defaults to VIRTIO when left UNSPECIFIED.
type TargetBus int32

const (
	TargetBus_TARGET_BUS_UNSPECIFIED TargetBus = 0
	TargetBus_TARGET_BUS_VIRTIO      TargetBus = 1
	TargetBus_TARGET_BUS_SCSI        TargetBus = 2
)

var TargetBus_name = map[int32]string{
	0: "TARGET_BUS_UNSPECIFIED",
	1: "TARGET_BUS_VIRTIO",
	2: "TARGET_BUS_SCSI",
}

var TargetBus_value = map[string]int32{
	"TARGET_BUS_UNSPECIFIED": 0,
	"TARGET_BUS_VIRTIO":      1,
	"TARGET_BUS_SCSI":        2,
}

func (x TargetBus) String() string {
	return proto.EnumName(TargetBus_name, int32(x))
}

func (TargetBus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// NodeLocalHotplugErrorCode is a machine-readable classification of
// failures returned by AttachDevice / DetachDevice.
type NodeLocalHotplugErrorCode int32

const (
	NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_OK                NodeLocalHotplugErrorCode = 0
	NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_INVALID_REQUEST   NodeLocalHotplugErrorCode = 1
	NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_VMI_NOT_FOUND     NodeLocalHotplugErrorCode = 2
	NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_VMI_UID_MISMATCH  NodeLocalHotplugErrorCode = 3
	NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_VMI_NOT_RUNNING   NodeLocalHotplugErrorCode = 4
	NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_HOST_PATH_INVALID NodeLocalHotplugErrorCode = 5
	NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_VOLUME_CONFLICT   NodeLocalHotplugErrorCode = 6
	NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_MOUNT_FAILED      NodeLocalHotplugErrorCode = 7
	NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_PATCH_FAILED      NodeLocalHotplugErrorCode = 8
	NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_LIBVIRT_TIMEOUT   NodeLocalHotplugErrorCode = 9
	NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_INTERNAL          NodeLocalHotplugErrorCode = 99
)

var NodeLocalHotplugErrorCode_name = map[int32]string{
	0:  "NODE_LOCAL_HOTPLUG_OK",
	1:  "NODE_LOCAL_HOTPLUG_INVALID_REQUEST",
	2:  "NODE_LOCAL_HOTPLUG_VMI_NOT_FOUND",
	3:  "NODE_LOCAL_HOTPLUG_VMI_UID_MISMATCH",
	4:  "NODE_LOCAL_HOTPLUG_VMI_NOT_RUNNING",
	5:  "NODE_LOCAL_HOTPLUG_HOST_PATH_INVALID",
	6:  "NODE_LOCAL_HOTPLUG_VOLUME_CONFLICT",
	7:  "NODE_LOCAL_HOTPLUG_MOUNT_FAILED",
	8:  "NODE_LOCAL_HOTPLUG_PATCH_FAILED",
	9:  "NODE_LOCAL_HOTPLUG_LIBVIRT_TIMEOUT",
	99: "NODE_LOCAL_HOTPLUG_INTERNAL",
}

var NodeLocalHotplugErrorCode_value = map[string]int32{
	"NODE_LOCAL_HOTPLUG_OK":                0,
	"NODE_LOCAL_HOTPLUG_INVALID_REQUEST":   1,
	"NODE_LOCAL_HOTPLUG_VMI_NOT_FOUND":     2,
	"NODE_LOCAL_HOTPLUG_VMI_UID_MISMATCH":  3,
	"NODE_LOCAL_HOTPLUG_VMI_NOT_RUNNING":   4,
	"NODE_LOCAL_HOTPLUG_HOST_PATH_INVALID": 5,
	"NODE_LOCAL_HOTPLUG_VOLUME_CONFLICT":   6,
	"NODE_LOCAL_HOTPLUG_MOUNT_FAILED":      7,
	"NODE_LOCAL_HOTPLUG_PATCH_FAILED":      8,
	"NODE_LOCAL_HOTPLUG_LIBVIRT_TIMEOUT":   9,
	"NODE_LOCAL_HOTPLUG_INTERNAL":          99,
}

func (x NodeLocalHotplugErrorCode) String() string {
	return proto.EnumName(NodeLocalHotplugErrorCode_name, int32(x))
}

func (NodeLocalHotplugErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Device describes a single host-side resource to expose to a VMI as a
// hotplug disk.
type Device struct {
	DevicePath string       `protobuf:"bytes,1,opt,name=device_path,json=devicePath" json:"device_path,omitempty"`
	Format     DeviceFormat `protobuf:"varint,2,opt,name=format,enum=kubevirt.nodelocalhotplug.v1.DeviceFormat" json:"format,omitempty"`
	TargetBus  TargetBus    `protobuf:"varint,3,opt,name=target_bus,json=targetBus,enum=kubevirt.nodelocalhotplug.v1.TargetBus" json:"target_bus,omitempty"`
	Serial     string       `protobuf:"bytes,4,opt,name=serial" json:"serial,omitempty"`
	Readonly   bool         `protobuf:"varint,6,opt,name=readonly" json:"readonly,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Device) GetDevicePath() string {
	if m != nil {
		return m.DevicePath
	}
	return ""
}

func (m *Device) GetFormat() DeviceFormat {
	if m != nil {
		return m.Format
	}
	return DeviceFormat_DEVICE_FORMAT_UNSPECIFIED
}

func (m *Device) GetTargetBus() TargetBus {
	if m != nil {
		return m.TargetBus
	}
	return TargetBus_TARGET_BUS_UNSPECIFIED
}

func (m *Device) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Device) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

type AttachDeviceRequest struct {
	Namespace  string  `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	VmiUid     string  `protobuf:"bytes,3,opt,name=vmi_uid,json=vmiUid" json:"vmi_uid,omitempty"`
	VolumeName string  `protobuf:"bytes,4,opt,name=volume_name,json=volumeName" json:"volume_name,omitempty"`
	Device     *Device `protobuf:"bytes,5,opt,name=device" json:"device,omitempty"`
}

func (m *AttachDeviceRequest) Reset()                    { *m = AttachDeviceRequest{} }
func (m *AttachDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*AttachDeviceRequest) ProtoMessage()               {}
func (*AttachDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AttachDeviceRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AttachDeviceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttachDeviceRequest) GetVmiUid() string {
	if m != nil {
		return m.VmiUid
	}
	return ""
}

func (m *AttachDeviceRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *AttachDeviceRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type AttachDeviceResponse struct {
	Success bool                      `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string                    `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Code    NodeLocalHotplugErrorCode `protobuf:"varint,3,opt,name=code,enum=kubevirt.nodelocalhotplug.v1.NodeLocalHotplugErrorCode" json:"code,omitempty"`
}

func (m *AttachDeviceResponse) Reset()                    { *m = AttachDeviceResponse{} }
func (m *AttachDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*AttachDeviceResponse) ProtoMessage()               {}
func (*AttachDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AttachDeviceResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AttachDeviceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AttachDeviceResponse) GetCode() NodeLocalHotplugErrorCode {
	if m != nil {
		return m.Code
	}
	return NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_OK
}

type DetachDeviceRequest struct {
	Namespace  string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	VmiUid     string `protobuf:"bytes,3,opt,name=vmi_uid,json=vmiUid" json:"vmi_uid,omitempty"`
	VolumeName string `protobuf:"bytes,4,opt,name=volume_name,json=volumeName" json:"volume_name,omitempty"`
}

func (m *DetachDeviceRequest) Reset()                    { *m = DetachDeviceRequest{} }
func (m *DetachDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*DetachDeviceRequest) ProtoMessage()               {}
func (*DetachDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DetachDeviceRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DetachDeviceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DetachDeviceRequest) GetVmiUid() string {
	if m != nil {
		return m.VmiUid
	}
	return ""
}

func (m *DetachDeviceRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

type DetachDeviceResponse struct {
	Success bool                      `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string                    `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Code    NodeLocalHotplugErrorCode `protobuf:"varint,3,opt,name=code,enum=kubevirt.nodelocalhotplug.v1.NodeLocalHotplugErrorCode" json:"code,omitempty"`
}

func (m *DetachDeviceResponse) Reset()                    { *m = DetachDeviceResponse{} }
func (m *DetachDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*DetachDeviceResponse) ProtoMessage()               {}
func (*DetachDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DetachDeviceResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DetachDeviceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DetachDeviceResponse) GetCode() NodeLocalHotplugErrorCode {
	if m != nil {
		return m.Code
	}
	return NodeLocalHotplugErrorCode_NODE_LOCAL_HOTPLUG_OK
}

func init() {
	proto.RegisterType((*Device)(nil), "kubevirt.nodelocalhotplug.v1.Device")
	proto.RegisterType((*AttachDeviceRequest)(nil), "kubevirt.nodelocalhotplug.v1.AttachDeviceRequest")
	proto.RegisterType((*AttachDeviceResponse)(nil), "kubevirt.nodelocalhotplug.v1.AttachDeviceResponse")
	proto.RegisterType((*DetachDeviceRequest)(nil), "kubevirt.nodelocalhotplug.v1.DetachDeviceRequest")
	proto.RegisterType((*DetachDeviceResponse)(nil), "kubevirt.nodelocalhotplug.v1.DetachDeviceResponse")
	proto.RegisterEnum("kubevirt.nodelocalhotplug.v1.DeviceFormat", DeviceFormat_name, DeviceFormat_value)
	proto.RegisterEnum("kubevirt.nodelocalhotplug.v1.TargetBus", TargetBus_name, TargetBus_value)
	proto.RegisterEnum("kubevirt.nodelocalhotplug.v1.NodeLocalHotplugErrorCode", NodeLocalHotplugErrorCode_name, NodeLocalHotplugErrorCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeLocalHotplug service

type NodeLocalHotplugClient interface {
	AttachDevice(ctx context.Context, in *AttachDeviceRequest, opts ...grpc.CallOption) (*AttachDeviceResponse, error)
	DetachDevice(ctx context.Context, in *DetachDeviceRequest, opts ...grpc.CallOption) (*DetachDeviceResponse, error)
}

type nodeLocalHotplugClient struct {
	cc *grpc.ClientConn
}

func NewNodeLocalHotplugClient(cc *grpc.ClientConn) NodeLocalHotplugClient {
	return &nodeLocalHotplugClient{cc}
}

func (c *nodeLocalHotplugClient) AttachDevice(ctx context.Context, in *AttachDeviceRequest, opts ...grpc.CallOption) (*AttachDeviceResponse, error) {
	out := new(AttachDeviceResponse)
	err := grpc.Invoke(ctx, "/kubevirt.nodelocalhotplug.v1.NodeLocalHotplug/AttachDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeLocalHotplugClient) DetachDevice(ctx context.Context, in *DetachDeviceRequest, opts ...grpc.CallOption) (*DetachDeviceResponse, error) {
	out := new(DetachDeviceResponse)
	err := grpc.Invoke(ctx, "/kubevirt.nodelocalhotplug.v1.NodeLocalHotplug/DetachDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeLocalHotplug service

type NodeLocalHotplugServer interface {
	AttachDevice(context.Context, *AttachDeviceRequest) (*AttachDeviceResponse, error)
	DetachDevice(context.Context, *DetachDeviceRequest) (*DetachDeviceResponse, error)
}

func RegisterNodeLocalHotplugServer(s *grpc.Server, srv NodeLocalHotplugServer) {
	s.RegisterService(&_NodeLocalHotplug_serviceDesc, srv)
}

func _NodeLocalHotplug_AttachDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeLocalHotplugServer).AttachDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.nodelocalhotplug.v1.NodeLocalHotplug/AttachDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeLocalHotplugServer).AttachDevice(ctx, req.(*AttachDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeLocalHotplug_DetachDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeLocalHotplugServer).DetachDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.nodelocalhotplug.v1.NodeLocalHotplug/DetachDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeLocalHotplugServer).DetachDevice(ctx, req.(*DetachDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeLocalHotplug_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubevirt.nodelocalhotplug.v1.NodeLocalHotplug",
	HandlerType: (*NodeLocalHotplugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AttachDevice",
			Handler:    _NodeLocalHotplug_AttachDevice_Handler,
		},
		{
			MethodName: "DetachDevice",
			Handler:    _NodeLocalHotplug_DetachDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/virt-handler/node-local-hotplug/v1/nodelocalhotplug.proto",
}

func init() {
	proto.RegisterFile("pkg/virt-handler/node-local-hotplug/v1/nodelocalhotplug.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0xb5, 0xb8, 0x76, 0xe9, 0xdd, 0x8d, 0xd6, 0x41, 0xd9, 0x4a, 0xd6, 0x48, 0x88, 0x89, 0x84,
	0x04, 0x08, 0xf8, 0xaa, 0x0f, 0x7c, 0x14, 0xad, 0x22, 0x6c, 0x06, 0xd8, 0x07, 0x1f, 0x6c, 0x86,
	0x76, 0x84, 0x66, 0xfb, 0x65, 0x67, 0xda, 0xc4, 0x37, 0xfd, 0x65, 0xfe, 0x1e, 0xff, 0x85, 0xe9,
	0xb4, 0xac, 0xa0, 0x04, 0x57, 0x5f, 0x7c, 0xbb, 0xf7, 0xdc, 0x9e, 0x3b, 0xf7, 0x9c, 0x7b, 0x53,
	0x78, 0x19, 0x5e, 0xad, 0xda, 0x89, 0x13, 0xf1, 0xe6, 0x9a, 0xf8, 0xb6, 0x4b, 0xa3, 0xb6, 0x1f,
	0xd8, 0xb4, 0xe9, 0x06, 0x16, 0x71, 0x9b, 0xeb, 0x80, 0x87, 0x6e, 0xbc, 0x6a, 0x27, 0x1d, 0x81,
	0x0a, 0x30, 0xc7, 0x5a, 0x61, 0x14, 0xf0, 0x00, 0x9d, 0x5f, 0xc5, 0x4b, 0x9a, 0xd2, 0x5b, 0xbf,
	0x7d, 0x90, 0x74, 0x6a, 0xdf, 0x25, 0x90, 0x87, 0x34, 0x71, 0x2c, 0x8a, 0x9e, 0xc0, 0x89, 0x2d,
	0x22, 0x33, 0x24, 0x7c, 0xad, 0x49, 0x55, 0xa9, 0xae, 0x60, 0xc8, 0xa0, 0x0b, 0xc2, 0xd7, 0xa8,
	0x0f, 0xf2, 0xc7, 0x20, 0xf2, 0x08, 0xd7, 0x0a, 0x55, 0xa9, 0x7e, 0xb7, 0xdb, 0x68, 0x1d, 0x6a,
	0xdd, 0xca, 0xda, 0x8e, 0x04, 0x03, 0xe7, 0x4c, 0x34, 0x02, 0xe0, 0x24, 0x5a, 0x51, 0x6e, 0x2e,
	0x63, 0xa6, 0xdd, 0x16, 0x7d, 0x9e, 0x1d, 0xee, 0x33, 0x17, 0xdf, 0xf7, 0x63, 0x86, 0x15, 0xbe,
	0x09, 0x51, 0x19, 0x64, 0x46, 0x23, 0x87, 0xb8, 0xda, 0x91, 0x98, 0x33, 0xcf, 0x50, 0x05, 0x8a,
	0x11, 0x25, 0x76, 0xe0, 0xbb, 0x9f, 0x35, 0xb9, 0x2a, 0xd5, 0x8b, 0xf8, 0x3a, 0xaf, 0x7d, 0x93,
	0xa0, 0xd4, 0xe3, 0x9c, 0x58, 0xeb, 0x6c, 0x34, 0x4c, 0x3f, 0xc5, 0x94, 0x71, 0x74, 0x0e, 0x8a,
	0x4f, 0x3c, 0xca, 0x42, 0x62, 0xd1, 0x5c, 0xf6, 0x4f, 0x00, 0x21, 0x38, 0x4a, 0x13, 0xa1, 0x59,
	0xc1, 0x22, 0x46, 0x67, 0x70, 0x9c, 0x78, 0x8e, 0x19, 0x3b, 0xb6, 0x90, 0xa0, 0x60, 0x39, 0xf1,
	0x9c, 0x85, 0x63, 0xa7, 0x1e, 0x26, 0x81, 0x1b, 0x7b, 0xd4, 0x14, 0x9c, 0x6c, 0x36, 0xc8, 0xa0,
	0x49, 0xca, 0x7c, 0x01, 0x72, 0xe6, 0xa8, 0x76, 0xa7, 0x2a, 0xd5, 0x4f, 0xba, 0x4f, 0x6f, 0xe2,
	0x21, 0xce, 0x39, 0xb5, 0x37, 0xf0, 0x60, 0x57, 0x00, 0x0b, 0x03, 0x9f, 0x51, 0xa4, 0xc1, 0x31,
	0x8b, 0x2d, 0x8b, 0x32, 0x26, 0xe6, 0x2f, 0xe2, 0x4d, 0x9a, 0x56, 0x3c, 0xca, 0x18, 0x59, 0x6d,
	0x04, 0x6c, 0xd2, 0xda, 0x57, 0x09, 0x4a, 0x43, 0xfa, 0x5f, 0xdd, 0x48, 0xf5, 0xec, 0x8e, 0xf0,
	0xef, 0x7a, 0x1a, 0x1f, 0xe0, 0x74, 0xfb, 0xe2, 0xd0, 0x63, 0x78, 0x34, 0xd4, 0x2f, 0x8d, 0x81,
	0x6e, 0x8e, 0xa6, 0xf8, 0x5d, 0x6f, 0x6e, 0x2e, 0x26, 0xb3, 0x0b, 0x7d, 0x60, 0x8c, 0x0c, 0x7d,
	0xa8, 0xde, 0x42, 0x67, 0x50, 0xda, 0x2d, 0xf7, 0xc7, 0xd3, 0xc1, 0x5b, 0x55, 0x42, 0x65, 0x40,
	0xbb, 0x85, 0x91, 0x31, 0xd6, 0xd5, 0x42, 0x63, 0x06, 0xca, 0xf5, 0x25, 0xa2, 0x0a, 0x94, 0xe7,
	0x3d, 0xfc, 0x4a, 0x9f, 0x9b, 0xfd, 0xc5, 0xec, 0x97, 0xce, 0x0f, 0xe1, 0xfe, 0x56, 0xed, 0xd2,
	0xc0, 0x73, 0x63, 0xaa, 0x4a, 0xa8, 0x04, 0xf7, 0xb6, 0xe0, 0xd9, 0x60, 0x66, 0xa8, 0x85, 0xee,
	0x97, 0x02, 0xa8, 0x93, 0xc0, 0xa6, 0xe3, 0x74, 0xef, 0xaf, 0xb3, 0xbd, 0xa3, 0x18, 0x4e, 0xb7,
	0xb7, 0x8c, 0x3a, 0x87, 0x6f, 0x64, 0xcf, 0x49, 0x57, 0xba, 0x7f, 0x43, 0xc9, 0x4d, 0x8f, 0x53,
	0x03, 0x6f, 0xfe, 0xec, 0x9e, 0xdb, 0xf9, 0xd3, 0xb3, 0xfb, 0x76, 0xdd, 0x3f, 0x7a, 0x5f, 0x48,
	0x3a, 0x4b, 0x59, 0xfc, 0xac, 0x9e, 0xff, 0x08, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x7e, 0x68, 0x72,
	0xed, 0x04, 0x00, 0x00,
}
